2024-01-08 14:47:59,597 [__main__:INFO] [main.py <19>: main.<module>] Logger successfully installed
2024-01-08 14:47:59,598 [__main__:INFO] [main.py <20>: main.<module>] Starting bot
2024-01-08 14:49:02,525 [__main__:DEBUG] [main.py <28>: main.start] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:02,526 [__main__:DEBUG] [main.py <38>: main.start] Connection to database(base): restarting bot for userid=861752892
2024-01-08 14:49:11,233 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:49:11,234 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:36,449 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=пќручни, correct=пќручни
2024-01-08 14:49:36,450 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:36,653 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:49:36,654 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:44,778 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=крем≈нь, correct=крем≈нь
2024-01-08 14:49:44,779 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:45,032 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:49:45,033 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:51,829 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=вернј, correct=вернј
2024-01-08 14:49:51,830 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:49:52,037 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:49:52,039 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:25,678 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=докум≈нт, correct=докум≈нт
2024-01-08 14:50:25,679 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:25,864 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:50:25,866 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:31,149 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=кќнусов, correct=кќнусов
2024-01-08 14:50:31,150 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:31,356 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:50:31,358 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:35,754 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=новост≈й, correct=новост≈й
2024-01-08 14:50:35,755 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:36,001 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:50:36,002 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:53,436 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=газопровќд, correct=газопровќд
2024-01-08 14:50:53,436 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:53,631 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:50:53,633 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:57,825 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=призџв, correct=призџв
2024-01-08 14:50:57,826 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:50:58,076 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:50:58,077 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:06,456 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=кр≈мн€, correct=кремня
2024-01-08 14:51:06,457 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:06,816 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:06,817 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:14,511 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=моза»чный, correct=моза»чный
2024-01-08 14:51:14,511 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:14,692 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:14,693 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:19,659 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=кремня, correct=кремня
2024-01-08 14:51:19,660 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:19,866 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:19,867 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:24,308 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=локтя, correct=лќкт€
2024-01-08 14:51:24,309 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:24,551 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:24,553 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:32,649 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=килом≈тр, correct=килом≈тр
2024-01-08 14:51:32,650 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:32,837 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:32,839 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:37,270 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=н≈друг, correct=н≈друг
2024-01-08 14:51:37,271 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:37,487 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:37,488 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:44,170 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=нам≈рение, correct=нам≈рение
2024-01-08 14:51:44,170 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:44,378 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:44,380 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:48,722 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=квартјл, correct=квартјл
2024-01-08 14:51:48,723 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:51:48,913 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:51:48,914 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:00,449 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=вероиспов≈дание, correct=вероиспов≈дание
2024-01-08 14:52:00,450 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:00,654 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:52:00,656 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:08,047 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=нефтепровќд, correct=нефтепровќд
2024-01-08 14:52:08,047 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:08,239 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:52:08,240 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:12,386 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=бќроду, correct=бќроду
2024-01-08 14:52:12,387 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:12,595 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:52:12,596 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:17,152 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=сирќты, correct=сирќты
2024-01-08 14:52:17,153 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:17,328 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:52:17,329 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:22,606 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=каталќг, correct=каталќг
2024-01-08 14:52:22,607 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:22,765 [__main__:DEBUG] [main.py <139>: main.start_solve_not_solved] Reply solve(not_solved) for userid=861752892
2024-01-08 14:52:22,766 [__main__:DEBUG] [main.py <143>: main.start_solve_not_solved] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:45,892 [__main__:DEBUG] [main.py <191>: main.check] Checking for userid=861752892 user_input=—топ, correct=лќкт€
2024-01-08 14:52:45,893 [__main__:DEBUG] [main.py <195>: main.check] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:45,893 [__main__:DEBUG] [main.py <28>: main.start] Connected to datebase(base) for userid=861752892
2024-01-08 14:52:45,894 [__main__:DEBUG] [main.py <38>: main.start] Connection to database(base): restarting bot for userid=861752892
2024-01-08 14:52:52,377 [__main__:DEBUG] [main.py <236>: main.top] Reply top for userid=861752892
2024-01-08 14:52:52,378 [__main__:DEBUG] [main.py <240>: main.top] Connected to datebase(base) for userid=861752892
